### ISSUE TITLE
Should the drainage tutorial work with dev branch?

### ISSUE THREAD

**Issue by AlisterH** [ItziModel/itzi#105]
I am getting a "math domain error" - included at the bottom of this description.

FWIW I am trying to run Itzi on Windows (without using WSL).  First I installed it in an OSGeo4W environment using the following steps:
- Install msvc build tools - in my case to D:\msvc.  I have no admin rights, so installed with https://github.com/Data-Oriented-House/PortableBuildTools
(this also works: https://gist.github.com/mmozeiko/7f3162ec2988e81e56d5c4e22cde9977#file-portable-msvc-py)
Presumably a more minimal install could be used.
- Run OSGeo4W setup and install python3-pip, python3-devel and python3-wheel.  I already had grass installed (and I think numpy), as QGIS dependencies.
- In the Osgeo4w Shell, run:
```
D:\msvc\setup.bat
set DISTUTILS_USE_SDK=1
pip install itzi
```
- Copy "D:\OSGeo4W\bin\grass82.bat" as "D:\OSGeo4W\bin\grass.bat"
- Update broken gcd import in D:\OSGeo4W\apps\Python39\lib\site-packages\networkx\algorithms\dag.py to say `from math import gcd`

This gave me an itzi install that worked for the Surface Modelling tutorial, but produced this error with the Drainage tutorial:
`AttributeError: 'DrainageSimulation' object has no attribute 'swmm5'`
After trying to figure out how to sort this out with master, I tried the dev branch:
```
pip uninstall itzi
python setup.py build
python setup.py install
```
or
```
pip uninstall itzi
pip install -e .
```
The new itzi install still works for the Surface Modelling tutorial, but now produces this error with the drainage modelling tutorial:
````  File "D:\OSGeo4W\apps\Python39\lib\site-
packages\itzi-20.5-py3.9-win-amd64.egg\itzi\drainage.py",
line 188, in get_linkage_flow
    math.pow(upstream_depth, 3/2.) *
ValueError: math domain error
````

**Comment by AlisterH** [comment]
Hmmm, investigating further:
`upstream_depth=-0.8583526611327983`

**Comment by AlisterH** [comment]
Actually, I was running with a different grid size somehow.  But switching to 5m, I do get the same error:
`upstream_depth=-0.747474670410142`

**Comment by lrntct** [comment]
Hi. This should work with version 25.4. I will close this for now. If still an issue, be free to reopen.
