### ISSUE TITLE
Itzi-SWMM simulation: AttributeError: 'DrainageSimulation' object has no attribute 'swmm5'

### ISSUE THREAD

**Issue by Caesar05** [ItziModel/itzi#104]
Hi everyone,
I tried to run the culvert modelling part of the Itzi tutorial by using the SWMM drainage model alongside the surface model.
Unfortunately I always recieve this error:

`GRASS nc_spm_08_grass7/PERMANENT:PERMANENT > itzi run parameter.ini 
Starting simulation of parameter.ini...                    
WARNING: Error during execution: Traceback (most recent call last):
  File "/home/julius/.local/lib/python3.8/site-packages/itzi-master/itzi/itzi.py", line 165, in sim_runner_worker
    sim_runner.initialize(conf_file).run().finalize()
  File "/home/julius/.local/lib/python3.8/site-packages/itzi-master/itzi/itzi.py", line 101, in initialize
    self.sim.initialize()
  File "/home/julius/.local/lib/python3.8/site-packages/itzi-master/itzi/simulation.py", line 144, in initialize
    self.__set_models(self.igis)
  File "/home/julius/.local/lib/python3.8/site-packages/itzi-master/itzi/simulation.py", line 118, in __set_models
    self.drainage = DrainageSimulation(self.rast_domain,
  File "/home/julius/.local/lib/python3.8/site-packages/itzi-master/itzi/drainage.py", line 39, in __init__
    self.swmm5 = swmm.Swmm5()
  File "/home/julius/.local/lib/python3.8/site-packages/itzi-master/itzi/swmm/swmm.py", line 37, in __init__
    self.c_swmm5 = c.CDLL(swmm_so)
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/julius/.local/lib/python3.8/site-packages/itzi-master/itzi/swmm/swmm_c.so: cannot open shared object file: No such file or directory
                    
Exception ignored in: <function DrainageSimulation.__del__ at 0x7fa98a6fe0d0>
Traceback (most recent call last):
  File "/home/julius/.local/lib/python3.8/site-packages/itzi-master/itzi/drainage.py", line 77, in __del__
    self.swmm5.swmm_end()
AttributeError: 'DrainageSimulation' object has no attribute 'swmm5'
`

I already deleted the swmm_c.c and flow.c files and explicitly compiled them by using the [programmers manual instruction](https://itzi.readthedocs.io/en/latest/prog_manual.html). Nevertheless, this seems to be not the solution for my issue.

Thanks for your help in advance.

**Comment by peterpan89** [comment]
I am now facing exactly this issue. Does anyone have a solution for this? Thanks for your help.

**Comment by cam1331** [comment]
Also facing the same issue in 2024, anyone found a solution to this?

**Comment by lrntct** [comment]
This is an installation error (the swmm extension not being built). It should work in version 25.4, as swmm is no longer part of itzi.
